SELECT HISTORY_ID,
       CAR_ID,
       DATE_FORMAT(START_DATE,'%Y-%m-%d') as START_DATE,
       DATE_FORMAT(END_DATE,'%Y-%m-%d') as END_DATE,
       IF(DATE_FORMAT(DATE_ADD(START_DATE, INTERVAL 29 DAY), '%Y-%m-%d') <= END_DATE, '장기 대여', '단기 대여') AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '%2022-09%'
ORDER BY history_id DESC;
